import esbuild from "esbuild";
import process from "process";
// import builtins from "builtin-modules";
// import { copy } from "esbuild-plugin-copy";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/index.js",
	// plugins: [
	// 	copy({
	// 		assets: [
	// 			{ from: "./manifest.json", to: "manifest.json" },
	// 			{ from: "./styles.css", to: "styles.css" },
	// 			{ from: "./.hotreload", to: ".hotreload" },
	// 		],
	// 		copyOnStart: true,
	// 		watch: true,
	// 	}),
	// ],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
